sonar.projectKey=realworld-react
sonar.projectName=RealWorld-React

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.jsx,**/*.spec.ts,**/*.spec.tsx
sonar.host.url=http://localhost:9000